# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d66af5d7f2a1ac2abff4b79655565f2aedc8cbaac62499207c4b85feb04186072f2c979bddd79b916ff42b970e2eab148d3463d5a55160c9250af1c35b803ea

test:
  secret_key_base: f38020bbf8813494cbdebc0153be7e28f1cdb1469e024d4c4eb4f566d4b8f5e7d4804076a4c83f131b66227d9c9e9be8b57a16f70793d0b03663b56d724f90c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
